import { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { CalendarDays, CheckCircle2, AlertTriangle, RefreshCw, Pencil } from 'lucide-react';
import { useAsync, useAuth } from '@/hooks';
import { matchService, memberService, scheduleService, seasonService, teamService } from '@/services';
import { ErrorState, LoadingState } from '@/components';

export function SchedulePage() {
  const { leagueId } = useParams<{ leagueId: string }>(); const { user } = useAuth(); const navigate = useNavigate();
  const [legs, setLegs] = useState<1 | 2>(1); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null); const [errorMessage, setErrorMessage] = useState<string | null>(null); const [refreshKey, setRefreshKey] = useState(0);
  const { data: membership, loading: membershipLoading } = useAsync(() => leagueId && user ? memberService.getMemberByUser(leagueId, user.id) : Promise.resolve(null), [leagueId, user?.id]);
  const { data: season, loading: seasonLoading } = useAsync(() => leagueId ? seasonService.getActiveSeason(leagueId) : Promise.resolve(null), [leagueId, refreshKey]);
  const { data: teams, loading: teamsLoading } = useAsync(() => leagueId ? teamService.getTeamsByLeague(leagueId) : Promise.resolve([]), [leagueId, refreshKey]);
  const { data: matches, loading: matchesLoading } = useAsync(() => leagueId ? matchService.getMatchesByLeague(leagueId) : Promise.resolve([]), [leagueId, refreshKey]);
  if (membershipLoading || seasonLoading || teamsLoading || matchesLoading) return <LoadingState />;
  if (!leagueId) return <ErrorState message="Liga no encontrada." />;
  const isOwner = membership?.status === 'active' && membership.role === 'owner';
  if (!isOwner) return <ErrorState message="Solo el dueño de la liga puede generar o ampliar el calendario." />;
  const regularMatches = (matches ?? []).filter(m => m.leagueId === leagueId && m.seasonId === season?.id && m.phase === 'regular');
  const rounds = new Set(regularMatches.map(m => m.round)).size; const teamCount = teams?.length ?? 0; const expectedRounds = teamCount % 2 === 0 ? teamCount - 1 : teamCount; const expectedMatches = teamCount >= 2 ? (teamCount * (teamCount - 1) * legs) / 2 : 0; const alreadyGenerated = regularMatches.length > 0;
  const handleGenerate = async () => { if (!user || !season) return; if (alreadyGenerated && !window.confirm('Ya existe un calendario. Se crearán únicamente los enfrentamientos que falten, por ejemplo los de equipos agregados después. Los partidos existentes no se moverán ni repetirán. ¿Continuar?')) return; if (!alreadyGenerated && !window.confirm(`Se generarán ${expectedMatches} partidos en ${expectedRounds * legs} jornadas. ¿Continuar?`)) return; try { setLoading(true); setErrorMessage(null); setMessage(null); const generated = await scheduleService.generateSeasonSchedule(leagueId, season.id, user.id, legs); setMessage(`Operación completada: ${generated.length} enfrentamientos nuevos o generados.`); setRefreshKey(k => k + 1); } catch (error) { setErrorMessage(error instanceof Error ? error.message : 'No se pudo generar el calendario.'); } finally { setLoading(false); } };
  return <div className="mx-auto max-w-4xl space-y-6 animate-fade-in"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold text-neutral-900">Generar calendario</h1><p className="mt-1 text-sm text-neutral-500">Genera el calendario automáticamente o amplíalo cuando agregues nuevos equipos.</p></div><button type="button" onClick={() => navigate(`/dashboard/leagues/${leagueId}/schedule-editor`)} className="inline-flex items-center justify-center gap-2 rounded-lg border border-neutral-200 bg-white px-4 py-2 text-sm font-semibold text-neutral-700 hover:bg-neutral-50"><Pencil size={16}/>Editar jornadas</button></div>
    {!season && <div className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800"><div className="flex items-start gap-3"><AlertTriangle size={18}/><div><p className="font-semibold">No hay una temporada activa</p><p className="mt-1">Activa una temporada antes de generar su calendario.</p></div></div></div>}
    {season && <><div className="card p-6"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-primary-50 text-primary-700"><CalendarDays size={24}/></div><div><p className="text-xs font-medium uppercase tracking-wide text-neutral-400">Temporada activa</p><h2 className="mt-1 text-lg font-bold text-neutral-900">{season.name}</h2><p className="mt-1 text-sm text-neutral-500">{teamCount} equipos · {regularMatches.length} partidos · {rounds} jornadas</p></div></div></div>
    <div className="card space-y-5 p-6"><div><h2 className="text-base font-semibold">Formato del calendario</h2><p className="mt-1 text-sm text-neutral-500">Al volver a ejecutar la generación, el sistema detecta los enfrentamientos faltantes y crea solo esos partidos, sin duplicar los existentes.</p></div><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => setLegs(1)} className={`rounded-xl border p-4 text-left ${legs === 1 ? 'border-primary-500 bg-primary-50' : 'border-neutral-200'}`}><p className="font-semibold">Una vuelta</p><p className="mt-1 text-sm text-neutral-500">Cada equipo enfrenta a todos una vez.</p></button><button type="button" onClick={() => setLegs(2)} className={`rounded-xl border p-4 text-left ${legs === 2 ? 'border-primary-500 bg-primary-50' : 'border-neutral-200'}`}><p className="font-semibold">Ida y vuelta</p><p className="mt-1 text-sm text-neutral-500">Los enfrentamientos se repiten con localía invertida.</p></button></div><div className="rounded-lg bg-neutral-50 p-4 text-sm text-neutral-600"><p><strong>{teamCount}</strong> equipos · <strong>{expectedRounds * legs}</strong> jornadas · <strong>{expectedMatches}</strong> partidos si se genera desde cero.</p></div>{message&&<div className="flex gap-3 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 size={18}/>{message}</div>}{errorMessage&&<div className="flex gap-3 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertTriangle size={18}/>{errorMessage}</div>}<button type="button" onClick={handleGenerate} disabled={loading || !season || teamCount < 2} className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-primary-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{loading?<RefreshCw size={17} className="animate-spin"/>:<CalendarDays size={17}/>} {loading?'Procesando...':alreadyGenerated?'Generar enfrentamientos faltantes':'Generar calendario automáticamente'}</button></div></>}
  </div>;
}
